---
- name: import postgresql repository key
  rpm_key:
    state: present
    key: "https://download.postgresql.org/pub/repos/yum/RPM-GPG-KEY-PGDG-{{ postgresql_short_version }}"
    validate_certs: yes
  when: postgresql_repo_gpgcheck | bool

- name: install postgresql repository
  yum_repository:
    name: postgresql
    baseurl: "{{ postgresql_repo_url }}"
    description: PostgreSQL upstream yum repository
    gpgcheck: "{{ postgresql_repo_gpgcheck }}"
    enabled: "{{ postgresql_repo_enabled }}"
